DROP TYPE Direccion FORCE;
DROP TYPE Persona FORCE;


-- DEFINICIÓN DE UN TIPO PARA DIRECCIÓN
CREATE OR REPLACE TYPE Direccion AS OBJECT(
    calle VARCHAR2(50),
    ciudad VARCHAR2(20),
    codigo_postal NUMBER(5)
);


-- DEFINICIÓN DE UN TIPO DE OBJETO 'PERSONA'
CREATE OR REPLACE TYPE Persona AS OBJECT(
    nombre VARCHAR2(50),
    apellidos VARCHAR2(100),
    domicilio DIRECCION, -- EL TIPO DE DATO DE UN ATRIBUTO PUEDE SER DE OTRO TIPO DE DATO OBJETO
    f_nac DATE,
    
    MEMBER FUNCTION calcularEdad RETURN NUMBER
    
) not final; -- PARA QUE LOS DEMÁS OBJETOS PUEDAN HEREDAR DE ESTE (final --> sería si no queremos que herede)


-- PARA DECIR QUE ALUMNO HEREDA DE PERSONA USAMOS UNDER
CREATE OR REPLACE TYPE Alumno UNDER Persona (
    matricula VARCHAR2(20),
    calificacion NUMBER
);

-- PARA ALTERAR UN OBJETO, USAMOS CASCADE PARA ELIMINARLO TAMBIÉN DE LOS OBJETOS QUE HAYAN HEREDADO ESE ATRIBUTO
ALTER TYPE Persona DROP ATTRIBUTE f_nac CASCADE;
-- PARA AÑADIRLO DE NUEVO
ALTER TYPE Persona ADD ATTRIBUTE f_nac DATE CASCADE;

CREATE OR REPLACE TYPE Profesor UNDER Persona (
    asignatura VARCHAR2(50),
    salario NUMBER,
    -- VA A TENER UN PROCEDIMIENTO DONDE LE PASEMOS POR PARÁMETRO EL SALARIO PARA AUMENTARLO (se puede poner cualquier nombre en salario)
    MEMBER PROCEDURE aumentoSalario (salario NUMBER)
);

-- DEFINIMOS EL CUERPO DE PERSONA (LOS MÉTODOS)
CREATE OR REPLACE TYPE BODY Persona AS 
    MEMBER FUNCTION calcularEdad RETURN NUMBER IS
    BEGIN
    -- Calcula los meses que hay entre la fecha actual y la fecha nacimiento, dividido entre 12, da los años
        RETURN MONTHS_BETWEEN(SYSDATE, f_nac) / 12;
    END calcularEdad;
    -- SI TUVIERA MÁS FUNCIONES Y PROCEDIMIENTOS SEGUIRÍAMOS AÑANDIENDO AQUÍ
    -- MEMBER PROCEDURE etc, etc,
END;

-- DEFINCIÓN DEL CUERPO DE PROFESOR (LOS MÉTODOS
CREATE OR REPLACE TYPE BODY Profesor AS
    MEMBER PROCEDURE aumentoSalario(salario NUMER) IS
    BEGIN
    -- SE USA EL SELF PARA DIFERENCIAR EL ATRIBUTO DE LA VARIABLE
        self.salario := self.salario + salario;
    END aumentoSalario;
END;

-- CREACIÓN DE TABLAS PARA ALMACENAR OBJETOS DE ALUMNO Y PROFESOR
CREATE TABLE Alumnos OF Alumno;
CREATE TABLE Profesores OF Profesor;
